create table if not exists public.hotels (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  rating numeric not null,
  location text not null,
  created_at timestamptz not null default now()
);

alter table public.hotels enable row level security;

drop policy if exists "Allow anon insert hotels" on public.hotels;
create policy "Allow anon insert hotels"
on public.hotels
for insert
to anon
with check (true);

drop policy if exists "Allow anon select hotels" on public.hotels;
create policy "Allow anon select hotels"
on public.hotels
for select
to anon
using (true);